name: zerotohero_orionlab
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - ipykernel
  - pip:
      - affine==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - bokeh==3.8.0
      - bottleneck==1.5.0
      - branca==0.8.1
      - brotli==1.1.0
      - cartopy==0.25.0
      - cftime==1.6.4.post1
      - click==8.2.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - cycler==0.12.1
      - dask==2025.7.0
      - distributed==2025.7.0
      - einops==0.8.1
      - fasteners==0.20
      - fiona==1.10.1
      - flox==0.10.4
      - folium==0.20.0
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - future==1.0.0
      - geocoder==1.38.1
      - geopandas==1.1.1
      - h5netcdf==1.6.4
      - h5py==3.14.0
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - inflate64==1.0.3
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lightning==2.5.4
      - lightning-utilities==0.15.2
      - llvmlite==0.44.0
      - locket==1.0.0
      - lz4==4.4.4
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - multivolumefile==0.2.3
      - nc-time-axis==1.4.1
      - netcdf4==1.7.2
      - numba==0.61.2
      - numbagg==0.9.0
      - numcodecs==0.13.1
      - numpy-groupies==0.11.3
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.4.0
      - partd==1.4.2
      - pexpect==4.9.0
      - pillow==11.3.0
      - planetary-computer==1.0.0
      - pooch==1.8.2
      - propcache==0.3.2
      - ptyprocess==0.7.0
      - py7zr==1.0.0
      - pyarrow==21.0.0
      - pybcj==1.0.6
      - pycryptodomex==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyppmd==1.2.0
      - pyproj==3.7.1
      - pyshp==2.3.1
      - pystac==1.13.0
      - pystac-client==0.9.0
      - python-box==7.3.2
      - python-dotenv==1.1.1
      - pytorch-lightning==2.5.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzstd==0.17.0
      - rasterio==1.4.3
      - rasterstats==0.20.0
      - ratelim==0.1.6
      - rioxarray==0.19.0
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - segmentation-models-pytorch==0.5.0
      - shapely==2.1.1
      - simplejson==3.20.1
      - simsimd==6.5.1
      - six==1.17.0
      - sparse==0.17.0
      - stackstac==0.5.1
      - stringzilla==3.12.6
      - sympy==1.14.0
      - tblib==3.1.0
      - texttable==1.7.0
      - tifffile==2025.5.10
      - timm==1.0.19
      - toolz==1.0.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchmetrics==1.8.1
      - torchvision==0.23.0
      - tqdm==4.67.1
      - triton==3.4.0
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - xarray==2025.6.1
      - xyzservices==2025.4.0
      - yarl==1.20.1
      - zarr==2.18.3
      - zict==3.0.0
      - zipp==3.23.0
